[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"
rust-version = "1.73"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grid = "0.9.0"
rand = "*"
serde_json = "*"

[dev_dependencies]
test-case = "2.2.2"
